### ISSUE TITLE
Error when RightObject is an empty object

### ISSUE THREAD

**Issue by holtalanm** [iRon7/Join-Object#23]
`GetProperties` errors out due to a null index if the RightObject is empty.

I have a use-case where my RightObject might be empty, but it also might not.  Didn't make sense to check if it was empty beforehand, as I  expected Merge-Object to handle it.  Ill see if I can submit a PR to fix.

**Comment by iRon7** [comment]
@holtalanm,

Thanks for the notification.
I actually already fixed the issue about a week ago (see #19 for details).
But I didn't release it as I wanted to combine it with a few other improvements.

Anyways, it is released now (version 3.4.6)
