### ISSUE TITLE
Merge array of objects

### ISSUE THREAD

**Issue by axelitus** [iRon7/Join-Object#26]
I'm not sure if I'm misunderstanding how the script works, but I can't seem to get the result I want.

I have two arrays of objects that have shared properties but also have different ones. Some objects are just in `$data1` and some of them are just in `$data2`:

```powershell
$data1 = @( [pscustomobject]@{ Id = "aaa"; Name = "Triple A"; SpecialValue = "Value for aaa only in data1" }, [pscustomobject]@{ Id = "bb"; Name = "Double B"; SpecialValue = "Value for bb only in data1" } )
$data2 = @( [pscustomobject]@{ Id = "bb"; Name = "2x B"; RandomValue = "Value for bb only in data2" }, [pscustomobject]@{ Id = "c"; Name = "Single C"; RandomValue = "Value for c only in data2" } )

$data1.Count
$data1 | FT

$data2.Count
$data2 | FT
```

Output:

```
2
Id  Name     SpecialValue
--  ----     ------------
aaa Triple A Value for aaa only in data1
bb  Double B Value for bb only in data1

2
Id Name     RandomValue
-- ----     -----------
bb 2x B     Value for bb only in data2
c  Single C Value for c only in data2
```

I tried to merge both arrays on `Id` using this command:

```powershell
$merged = $data1 | Merge-Object $data2 -On Id
$merged | FT
```

And what I get is this:

```
Id Name             SpecialValue               RandomValue
-- ----             ------------               -----------
bb {Double B, 2x B} Value for bb only in data1 Value for bb only in data2
```

I was expecting to get this result instead:

```
Id  Name     SpecialValue                RandomValue
--  ----     ------------                -----------
aaa Triple A Value for aaa only in data1
bb  2x B     Value for bb only in data1  Value for bb only in data2
c  Single C                              Value for c only in data2
```

Am I missing something? Is this how it's supposed to work? Is what I want achievable with this script?

**Comment by axelitus** [comment]
I managed to get it working using the command:

```powershell
$merged = $data1 | Join $data2 -On Id -JoinType Full -Property @{ '*' = 'Right.*' }
```

I thought that as the Merge command is an alias with default parameters it should work using the Merge command:

```powershell
Copy-Command -Command $JoinCommand -Name Merge-Object     -Default @{ JoinType = 'Full'; Property = @{ '*' = 'Right.*' } }; Set-Alias Merge  Merge-Object
```

But it is not the case. I have to be explicit with all Parameters for it to work.

**Comment by iRon7** [comment]
Your expectation is right,

> the Merge command is an alias with default parameters it should work using the Merge command

And indeed works that way at my side (version `3.4.6`):

```PowerShell
PS C:\> $data1 | Merge-Object $data2 -On Id

Id  Name     SpecialValue                RandomValue
--  ----     ------------                -----------
aaa Triple A Value for aaa only in data1
bb  2x B     Value for bb only in data1  Value for bb only in data2
c   Single C                             Value for c only in data2
```

Could it be that your `Merge-Object` command is overwritten somehow at your side?
```PowerShell
PS C:\> get-command Merge-Object

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Function        Merge-Object

PS C:\> $PSDefaultParameterValues

Name                           Value
----                           -----
InnerJoin-Object:JoinType      Inner
Update-Object:JoinType         Left
Update-Object:Property         {*}
CrossJoin-Object:JoinType      Cross
LeftJoin-Object:JoinType       Left
Merge-Object:Property          {*}
Merge-Object:JoinType          Full
FullJoin-Object:JoinType       Full
RightJoin-Object:JoinType      Right
```

What PowerShell version are you using?

**Comment by axelitus** [comment]
The command itself is not being overwritten, but the `PSDefaultParameterValues` var is empty:
![image](https://user-images.githubusercontent.com/732441/116452843-c9ece780-a823-11eb-9a34-9dca111f5772.png)

I am including your script as part of an internal module library I'm writing to get information from Azure. As I understand, the script should work as it is as nothing is being changed except the bundling.

I searched your script and see that it is being populated in the Copy-Command (which is being executed as all the aliases are available):
![image](https://user-images.githubusercontent.com/732441/116453426-7cbd4580-a824-11eb-8658-de09e7ee5b90.png)

As I am bundling it in a module, could it be that the var needs to be "exported" and that is why it is empty?

**Comment by axelitus** [comment]
I have checked and the module is exporting all variables, so it should work; Here's a snip of the module file `Join.psd1`:
![image](https://user-images.githubusercontent.com/732441/116454175-53e98000-a825-11eb-8cfe-3bae4f0facad.png)

**Comment by axelitus** [comment]
I tried with both: Powershell 5.1 and Powershell 7.1.3:
![image](https://user-images.githubusercontent.com/732441/116456968-78932700-a828-11eb-8fe1-c8b2b8217661.png)
![image](https://user-images.githubusercontent.com/732441/116457006-82b52580-a828-11eb-8c51-4156ecc33f91.png)


In both cases, it's behaving the same.

**Comment by iRon7** [comment]
@axelitus,
I think that your issue is described in StackOverflow question: [Set $PSDefaultParametersValues for use within Module Scope](https://stackoverflow.com/a/30427401/1701026).
It is actually on my to do list to migrate the script to a module ([`#22` Move to module (psm1)](https://github.com/iRon7/Join-Object/issues/22)), I guess that at that time, I will run in the same issue.
Anyways, I suspect that the solution would be to build function _wrappers_ (rather _proxy_ functions) in your module.

**Comment by axelitus** [comment]
Indeed I think that is what is happening. At the moment I'm fine with the workaround (using the full command call), but now it is clear to me why it is happening and for future reference why it won't work as expected using the aliases.

Hopefully, you can make it as a module and resolve this issue in a simple way! Let me know if you need any help with it o with testing.

I'll close this now as it won't be fixed until #22 and it is not an issue for me anymore now that I know what is happening, its merely an inconvenience as the script works fine.

**Comment by iRon7** [comment]
FYI: I have created a module version (`JoinModule`) of the `Join-Object` script.
Excerpt from the `ReadMe`:

Installation
------------
There are two versions of this `Join-Object` cmdlet (both versions supply the same functionality):

* [**Join Module**](https://www.powershellgallery.com/packages/JoinModule)

<span></span>

    Install-Module -Name JoinModule

* [**Join Script**](https://www.powershellgallery.com/packages/Join)

<span></span>

    Install-Script -Name Join

(Or rename the `Join.psm1` module to a `Join.ps1` script file) and invoked the script by [**dot sourcing**](https://docs.microsoft.com/powershell/module/microsoft.powershell.core/about/about_scripts?view=powershell-6#script-scope-and-dot-sourcing): 

    . .\Join.ps1`

**Comment by axelitus** [comment]
Awesome! I have updated my library to remove the script's inclusion and use the published module instead!

It's working fine and now I don't have to maintain it inside my library. Thanks a lot for your efforts!
