### ISSUE TITLE
how to use where keyword

### ISSUE THREAD

**Issue by ericxin1982** [iRon7/Join-Object#31]
HI @iRon7 

Thanks for doing the good job to make this module be available.
I am wondering how to use where keyword, there is no example available, sorry to bother you.

Thanks
Eric Xin

**Comment by iRon7** [comment]
Hello Eric,

I don't think the `-Where` parameter is used much as it is quiet similar to just piping the result to the [`Where-Object`](https://docs.microsoft.com/powershell/module/microsoft.powershell.core/where-object) cmdlet. Yet there is a minor difference as it lets you access to properties of the `$Left` and `$Right` prior they where merged. Meaning you might do something like `-On Name -Where { $Left.Id -gt $Right.Id }` which will than only pass the objects where the `Name` properties are equal and the `Id` at the left side is greater than the `Id` at the right side. There are also a few examples in the [pester test script](https://github.com/iRon7/Join-Object/blob/master/Tests/Join.Tests.ps1).

**Comment by ericxin1982** [comment]
Thanks so much!
