### ISSUE TITLE
multiple join like sql syntax

### ISSUE THREAD

**Issue by ericxin1982** [iRon7/Join-Object#36]
Hi @iRon7 

If I have multiple columns need to be joined, is it feasible? The example you gave is single column join.

Thanks
Eric Xin

**Comment by iRon7** [comment]
I am not sure if I get the question but you might do:
* `-on Column1,Column2`  
  which would mean that in order the objects to be joined:
  * The value of `Column1`  of the left object needs to be equal to the right value  of `Column1` of the right object, and
  * The value of `Column2`  of the left object needs to be equal to the right value  of `Column2` of the right object
* `-on Column1,Column2 -eq Column3,Column4 `  
  which would mean that in order the objects to be joined:
  * The value of `Column1`  of the left object needs to be equal to the right value  of `Column3` of the right object, and
  * The value of `Column2`  of the left object needs to be equal to the right value  of `Column4` of the right object

If this doesn't answer the question, can you supply me with a [create a Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)?

**Comment by ericxin1982** [comment]
ok, thanks. let me try.

**Comment by ericxin1982** [comment]
I have tried, the multiple on I think it works, but the leftjoin is unexpected.

$( $left | leftjoin $right -On zip,usstate,rectype,season -Equals zip,usstate,rectype,season) | export-csv -Path \\192.168.168.208\csv\

the $left is 32 rows, and $right is 12rows,  typed the command above, it looks like it become full-join, that is not what I wanted.
Why it is like that. The total row is 44 rows.

See below, it is duplicated.
![image](https://user-images.githubusercontent.com/9047436/224883185-062d0630-ba3e-4b97-bc1a-abc24cfa9722.png)

**Comment by iRon7** [comment]
To be able to simulate what you are doing, please paste the concerned object lists (`$Left |ConvertTo-Csv |Clip` and `$Right |ConvertTo-Csv |Clip`) into this issue.

**Comment by ericxin1982** [comment]
Hi @iRon7 

I figured out, I added one more column for on and equal then the duplicated rows varnish.

Thanks
Eric Xin
