### ISSUE TITLE
Join on a 2 different keys

### ISSUE THREAD

**Issue by chaoscreater** [iRon7/Join-Object#4]
If I'm trying to join 2 tables pulled from 2 data sources, the keys are named differently. One is named "UserID", the other is named "ID". The data sources are static and can't be modified, but the data in both tables are relevant to each other. How can I join e.g. table1.userID to table2.ID ?

**Comment by iRon7** [comment]
You can you two tables with different keys as follows:
`$Table1 | Join $Table2 -On userID -Equal ID`
