### ISSUE TITLE
Replace Foreach-Object with Foreach or For?

### ISSUE THREAD

**Issue by burkasaurusrex** [iRon7/Join-Object#6]
Foreach ends up being about twice as fast in simple tests - I wonder if it would speed up Join-Object?

```powershell
Measure-Command { 0..1000000 | Foreach-Object $_ }

Measure-Command { foreach ($i in 0..1000000) {$i} }

Measure-Command { for ($i = 0; $i -lt 1000000; $i++) {$i} }
```

**Comment by iRon7** [comment]
@burkasaurusrex, sorry for the late response (I didn't get any notifications for new issues).
Anyways, I coincidentally removed the `For` commands last update to better support DataTables. I will do some performance testing between using the `ForEach-Object` cmdlet and the `ForEach` command in this `Join-Object` cmdlet soon and let you know the results.

**Comment by iRon7** [comment]
@burkasaurusrex, 
Thanks for the hint, on larger tables (of a few 1000 objects), there is indeed a performance increase of almost 2 times by using the `ForEach` command rather than the `ForEach-Object` cmdlet.
I have uploaded a new version (3.0.6) with this enhancement.
